Fail in case build wasn't done correctly

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -40,6 +40,14 @@ jobs:
         working-directory: ./packages/yoroi-extension
         run: npm run test:build:mainnet
 
+      - name: Check if the app is built correctly
+        working-directory: ./packages/yoroi-extension/build/js
+        run: |
+          if [ ! -f inject.js ]; then
+            echo "Build failed: files not found"
+            exit 1
+          fi
+
       - name: Archive built app
         uses: actions/upload-artifact@v4
         with:
